version: "3.7"
services:
  #api:
  #  container_name: backend
  #  build: .
  #  tty: true
  #  ports:
  #    - "5101:5101"

 pgdb:
   image: postgres:latest
   ports: ["5432:5432"]
   environment:
    - POSTGRES_DB=test
    - POSTGRES_PASSWORD=password
    - TZ=Asia/Tokyo
   command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    #network_mode: "host"
